graph LR
    subgraph ThisNode["Abstraction"]

        s_in@{ shape: small-circle, label: "Incoming slot" }
        s_out@{ shape: framed-circle, label: "Outgoing slot" }
        s_out_abs@{ shape: framed-circle, label: "Outgoing slot" }

        s_in --> L_mrf("[name].mrf")
        s_in --> L_bypass("[name]".bypass)
        s_in --> L_abs("[name]".abstraction)


        L_mrf --> s_out
        L_bypass --> s_out
        L_abs --> s_out_abs


    end

    U(Upstream) --> s_in
    s_out -->|River| D1(Downstream 1)
    s_out_abs -->|Abstraction| D2(Downstream 2)

    class L_mrf linkNode;
    class L_bypass linkNode;
    class L_abs linkNode;
    class ThisNode thisNode;
    class s_in slot;
    class s_out slot;
    class s_out_abs slot;