graph LR
    subgraph ThisNode["Link"]

        s_in@{ shape: small-circle, label: "Incoming slot" }
        s_out@{ shape: framed-circle, label: "Outgoing slot" }

        L("[name]")

        s_in --> L --> s_out

    end

    U(Upstream) --> s_in
    s_out --> D1(Downstream)

    class L linkNode;
    class ThisNode thisNode;
    class s_in slot;
    class s_out slot;