graph LR
    subgraph ThisNode["Reservoir (with output outflow)"]

        s_in@{ shape: small-circle, label: "Incoming slot" }
        s_out@{ shape: framed-circle, label: "Storage slot" }
        L_rain("[name].rainfall")
        L_spill("[name].spill")
        L_comp("[name].compensation")
        O_outflow("[name].outflow")
        O_evap("[name].evaporation")
        O_leak("[name].leakage")
        S("[name]")

        s_in --> S --> s_out

        L_rain --> S
        S --> L_spill --> O_outflow
        S --> O_evap
        S --> O_leak
        S -.-> L_comp -.-> O_outflow

    end

    U(Upstream) --> s_in
    s_out -->|Storage| D1(Downstream 1)
    class L_rain linkNode;
    class L_spill linkNode;
    class L_comp linkNode;
    class O_outflow outputNode;
    class O_evap outputNode;
    class O_leak outputNode;
    class S storageNode;
    class ThisNode thisNode;
    class s_in slot;
    class s_out slot;
