graph LR
    subgraph ThisNode["River"]

        subgraph AG1["Aggregated node"]
            L_net
            O_loss
        end
    
        s_in@{ shape: small-circle, label: "Incoming slot" } 
        s_out@{ shape: framed-circle, label: "Outgoing slot" }
        
        s_in --> O("[name].inflow") 
        O -.->|Routing| I
        I("[name].outflow")

        I --> L_net("[name].net") --> s_out
        I --> O_loss("[name].loss")
        
               
    end

    U(Upstream) --> s_in
    s_out --> D1(Downstream )

    class I inputNode;    
    class O outputNode;    
    class O_loss outputNode;    
    class L_net linkNode;     
    class ThisNode thisNode;
    class AG1 aggNode;
    class s_in slot;
    class s_out slot;