[package]
name = "ipm-ocl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipm-common = { path = "../ipm-common" }
nalgebra-sparse = "0.10.0"
ocl = "0.19"
log = "0.4.19"
