[package]
name = "ipm-ocl"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipm-common = { path = "../ipm-common" }
nalgebra-sparse = "0.11.0"
ocl = "0.19"
log = "0.4.28"
