[package]
name = "ipm-simd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipm-common = { path = "../ipm-common" }
nalgebra-sparse = "0.10.0"
log = "0.4.19"
colamd = "0.1.0"
